name: Dockerimage 1.6.x

on:
  push:
    branches: 
      - master
    paths:
      - "**-16x.yml"
      - "Dockerfile.16x"

jobs:
  handbrake:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Build the Docker image
      env:
        HUB_NAME: ${{ secrets.DOCKER_NAME }}
        HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u $HUB_NAME -p $HUB_KEY
        docker build . --pull --no-cache --file Dockerfile.16x --tag zocker160/handbrake-nvenc:16x

        docker push zocker160/handbrake-nvenc:16x
