name: Dockerimage 1.8.x

on:
  push:
    branches:
      - master
    paths:
      - "**-18x.yml"
      - "Dockerfile"

jobs:
  handbrake:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Build the Docker image
      env:
        HUB_NAME: ${{ secrets.DOCKER_NAME }}
        HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u $HUB_NAME -p $HUB_KEY
        docker build . --pull --no-cache --file Dockerfile --tag zocker160/handbrake-nvenc:latest

        docker tag zocker160/handbrake-nvenc:latest zocker160/handbrake-nvenc:18x

        # disabled for now as it is kinda broken
        #docker push zocker160/handbrake-nvenc:latest
        docker push zocker160/handbrake-nvenc:18x
